[
  {
    "_description": "This file is used for local debugging. It is a heavily truncated version of the actual output that the API will provide.",
    "tag_name": "v1.4.0-beta.3",
    "name": "v1.4.0-beta.3",
    "prerelease": true,
    "published_at": "2018-06-23T00:45:18Z",
    "assets": [
      {
        "browser_download_url": "https://github.com/raiguard/ModernGadgets/releases/download/v1.4.0-beta.3/ModernGadgets_1.4.0-beta.3.rmskin"
      }
    ],
    "body": "- Added tentative Snapdragon support to CPU Meter\r\n- Added support for CoreTemp and Speedfan in CPU Meter\r\n- Added dynamic fan display to CPU Meter\r\n- Increased supported threads in CPU Meter from 36 to 64 (AMD Threadripper 2)\r\n- Updated dynamic settings system with more consistent and flexible functions\r\n- Updated LoadSkin and UpdateChecker scripts for Rainmeter 4.2 compatibility\r\n- Settings backups are now made upon closing a settings skin, rather than at a preset interval\r\n- Fixed error with the update checker reading a file while it was being written by WebParser"
  },
  {
    "tag_name": "v1.3.1",
    "name": "v1.3.1",
    "prerelease": false,
    "published_at": "2018-05-03T01:56:11Z",
    "assets": [
      {
        "browser_download_url": "https://github.com/raiguard/ModernGadgets/releases/download/v1.3.1/ModernGadgets_1.3.1.rmskin"
      }
    ],
    "body": "- Fixed development testing opt-in not working"
  }
]